#!/usr/bin/env bash
# vps-setup.sh — idempotent setup for Ollama-on-VPS for DACN
#
# Usage (on VPS as root):
#   1. Edit OLLAMA_TOKEN below or set it via env:  export OLLAMA_TOKEN="..."
#   2. (Optional) Edit ALLOWED_SSH_CIDR to restrict SSH source
#   3. bash vps-setup.sh
#
# What it does:
#   - Forces Ollama to bind 127.0.0.1:11434 (so it's NOT exposed by default)
#   - Installs Caddy as reverse proxy on :80 with bearer-token auth
#   - Configures ufw firewall: SSH + 80 only, deny 11434
#
# Idempotent: safe to re-run. Each step checks current state before changing.

set -euo pipefail

# ─────────────────────────────── config ──────────────────────────────────────
OLLAMA_TOKEN="${OLLAMA_TOKEN:-CHANGE_ME_BEFORE_RUNNING}"
# Restrict SSH to a CIDR (your home/uni IP range). Use "any" to allow from anywhere.
ALLOWED_SSH_CIDR="${ALLOWED_SSH_CIDR:-any}"
CADDYFILE_PATH="/etc/caddy/Caddyfile"
OLLAMA_OVERRIDE_DIR="/etc/systemd/system/ollama.service.d"
OLLAMA_OVERRIDE_FILE="${OLLAMA_OVERRIDE_DIR}/override.conf"
# ─────────────────────────────────────────────────────────────────────────────

if [[ "${OLLAMA_TOKEN}" == "CHANGE_ME_BEFORE_RUNNING" ]]; then
    echo "ERROR: set OLLAMA_TOKEN env var or edit this script before running." >&2
    echo "Example:  OLLAMA_TOKEN=\$(openssl rand -hex 32) bash vps-setup.sh" >&2
    exit 1
fi

if [[ "${EUID}" -ne 0 ]]; then
    echo "ERROR: must run as root (use sudo)." >&2
    exit 1
fi

echo "==> [1/5] Pin Ollama to 127.0.0.1:11434"
mkdir -p "${OLLAMA_OVERRIDE_DIR}"
cat > "${OLLAMA_OVERRIDE_FILE}" <<'EOF'
[Service]
Environment="OLLAMA_HOST=127.0.0.1:11434"
EOF
systemctl daemon-reload
if systemctl is-active --quiet ollama; then
    systemctl restart ollama
else
    systemctl start ollama
fi
echo "    Ollama bound to localhost only."

echo "==> [2/5] Install Caddy (if missing)"
if ! command -v caddy >/dev/null 2>&1; then
    apt-get update -qq
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl
    curl -fsSL 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -fsSL 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq
    apt-get install -y -qq caddy
else
    echo "    Caddy already installed: $(caddy version)"
fi

echo "==> [3/5] Write Caddyfile with bearer-token auth"
cat > "${CADDYFILE_PATH}" <<EOF
# DACN Ollama reverse proxy — bearer token auth, plaintext HTTP (no TLS w/o domain)
# Generated by infra/vps-setup.sh

:80 {
    @auth header Authorization "Bearer ${OLLAMA_TOKEN}"

    handle @auth {
        reverse_proxy 127.0.0.1:11434 {
            # CPU inference for 5B-8B is slow (~3 tok/s). Bump timeouts so
            # Caddy doesn't 502 on long generates. Match these with the
            # client-side OLLAMA_TIMEOUT env var (default 180s, recommend 600s).
            transport http {
                dial_timeout       10s
                response_header_timeout 600s
                read_timeout       600s
            }
        }
    }

    handle {
        respond "Unauthorized" 401 {
            close
        }
    }

    log {
        output file /var/log/caddy/ollama-access.log {
            roll_size 10mb
            roll_keep 5
        }
        format json
    }
}
EOF
mkdir -p /var/log/caddy
chown -R caddy:caddy /var/log/caddy 2>/dev/null || true
systemctl reload caddy 2>/dev/null || systemctl restart caddy
echo "    Caddy reloaded."

echo "==> [4/5] Configure ufw firewall"
if ! command -v ufw >/dev/null 2>&1; then
    apt-get install -y -qq ufw
fi
# Reset rules quietly to be idempotent
ufw --force reset >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
if [[ "${ALLOWED_SSH_CIDR}" == "any" ]]; then
    ufw allow OpenSSH >/dev/null
else
    ufw allow from "${ALLOWED_SSH_CIDR}" to any port 22 proto tcp >/dev/null
fi
ufw allow 80/tcp >/dev/null
ufw deny 11434/tcp >/dev/null
ufw --force enable >/dev/null
echo "    ufw enabled."
ufw status verbose

echo "==> [5/5] Smoke test (local loopback + external via Caddy)"
echo "  -- direct (should return JSON tag list):"
curl -s --max-time 5 http://127.0.0.1:11434/api/tags | head -c 200; echo
echo "  -- via Caddy without token (should be 401):"
curl -s -o /dev/null -w "HTTP %{http_code}\n" --max-time 5 http://127.0.0.1/api/tags
echo "  -- via Caddy with token (should be 200):"
curl -s -H "Authorization: Bearer ${OLLAMA_TOKEN}" --max-time 5 http://127.0.0.1/api/tags | head -c 200; echo

cat <<EOF

==> DONE.

From your dev machine, test reachability:
  curl -H "Authorization: Bearer ${OLLAMA_TOKEN}" http://157.245.195.74/api/tags
  curl -H "Authorization: Bearer ${OLLAMA_TOKEN}" http://157.245.195.74/api/generate \\
       -d '{"model":"gemma4:e2b","prompt":"hello","stream":false}'

Save this in your project .env.local (NOT committed):
  OLLAMA_BASE_URL=http://157.245.195.74
  OLLAMA_TOKEN=${OLLAMA_TOKEN}

If Caddy logs show abuse, rotate token by re-running this script with a new OLLAMA_TOKEN.
EOF
